version: "3"
services:
  frontend:
    container_name: prime-pianist-frontend
    restart: always
    build: ./client
    ports:
      - "3000:3000"
  backend:
    container_name: prime-pianist-backend
    restart: always
    build: ./backend
    ports:
      - '5000:5000'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: prime-pianist-database
    image: mongo
    ports:
      - '27017:27017'
    


