version: "3"
services:
  frontend:
    container_name: prime-pianist-frontend
    restart: always
    build: ./client
    ports:
      - "3000:80"
  backend:
    container_name: prime-pianist-backend
    restart: always
    build: ./backend
    ports:
      - '5000:5000'
    


